name: Piotr Kosmowski site
markdown: redcarpet
safe: true
lsi: false
pygments: true
encoding: utf-8
baseurl: http://kospiotr.github.io
basesourceurl: https://github.com/kospiotr/kospiotr.github.io/edit/master
permalink: /blog/:year/:month/:day/:title/